name: Automatic build

on:
  schedule:
    - cron: '0 2 1 * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run:  |
        sudo apt install -y python3-pip libcap-dev musl musl-tools
        sudo pip3 install meson ninja

    - name: Build for x86_64
      run:  ./build_in_chroot.sh x86_64
  
    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          bwrap*
          libbwrap*
