name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2

    - name: Build (Linux, Musl libc, static, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, aarch64)
      run: ARCH=aarch64 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, x86)
      run: ARCH=x86 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, arm)
      run: ARCH=arm OS=linux LIBC=musleabi ./build.sh

    - name: Build (Linux, Musl libc, static, riscv64)
      run: ARCH=riscv64 OS=linux LIBC=musl ./build.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          bwrap*
